Repository ConducereIT/APV, pull requests merged in 2024-04, with the labels that each got.

#10 Added Faq
  client/src/App.tsx
  client/src/components/Faqs.component.tsx
  client/src/config/FaqConfig.ts
  client/src/views/Faq.view.tsx
Labels: invalid

#13 Add workflow for main branch
  .github/workflows/main.yml
  .gitignore
Labels: READY TO MERGE

#27 Auth
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/main.tsx
  client/src/routes/AllRoutes.tsx
  client/src/views/Account.view.tsx
  client/src/views/Login.view.tsx
  server/backend.ts
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20240408145820_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
Labels: Work in progress

#69 Mailer
  server/backend.ts
  server/config/racesConfig.ts
  server/mailer.ts
  server/package-lock.json
  server/package.json
Labels: READY TO MERGE
